/advanced_motion_planner/lidar_offset: rad(pi/2.0)
/advanced_motion_planner/max_scan_range: 2.5

/advanced_motion_planner/min_speed: 0.30
/advanced_motion_planner/max_speed: 1.00
/advanced_motion_planner/speed_incr: 0.01

/advanced_motion_planner/follow_wall_x: 1
/advanced_motion_planner/min_wall_distance: 0.1

/advanced_motion_planner/min_observation_angle: 0.40
/advanced/motion/planner/max_observation_angle: 0.75
